### ISSUE TITLE
Download path of flow-azuretm.zip incorrect 

### ISSUE THREAD

**Issue by anirban-sap** [SAP-samples/btp-services-intelligent-routing#11]
The download path https://github.com/SAP-samples/btp-cloud-integration-intelligent-routing/blob/main/02-SetupMonitoringEndpoint/flow-azuretm.zip returns page not found. The file location has changed.

**Comment by mahesh0431** [comment]
Thanks, @anirban-sap, for finding this! It's fixed now.
