### ISSUE TITLE
[Question] : SAP BTP Multi-Region reference architectures for High Availability and Resiliency

### ISSUE THREAD

**Issue by namratasurendranath** [SAP-samples/btp-services-intelligent-routing#12]
We are trying to implement SAP BTP Multi-Region reference architectures for High Availability and Resiliency.

We have deployed nodeJS application (microservice) to Cloud Foundry in Canada (ca10) region. This application basically provides https REST endpoint. Consumer applications need to authenticate using OAuth 2.0 before they can use this application. We want to avoid any downtime to this application due to planned BTP downtimes (quarterly max 4 hrs) and even any unplanned downtimes. We want to implement multi-region architecture by deploying this nodeJS application in lets say Europe region- cloud foundry subaccount too in addition to canada region. We referred SAP's reference architecture and decided to use AWS Route53 for DNS failover load balancer. 

<img width="564" alt="image" src="https://github.com/user-attachments/assets/24f1bba5-4cfe-49dc-9a83-e7029b57716f">

However, we dont understand how consumer applications can access authenticate against nodeJS application using OAuth 2.0 since service keys for XSUAA application in both regions (subaccounts) will be different. Consumer applications will have to use 2 different OAuth 2.0 token endpoints. If they have cached token from Canada region, it wont work for Europe region. Also if they cannot fetch token from Canada region (if its down), , they will have to fetch token from Europe region using separate URL. We were recommended IAS, however the problem remains same as IAS is also subaccount specific service and will have planned downtimes. Can this problem be resolved?

**Comment by anirban-sap** [comment]
@mahesh0431 @maxstreifeneder - could you take a look at this?

**Comment by mahesh0431** [comment]
@NARAYANAGAYATHRI IAS is multi-region enabled you can check here the documentation: https://help.sap.com/docs/cloud-identity-services/cloud-identity-services/disaster-recovery-high-availability .

**Comment by namratasurendranath** [comment]
Hello @mahesh0431 : Is that your recommended reference architecture for enabling BTP multi region? IAS then becomes a mandatory component in this architecture which can synchronize a common set of credentials for the BTP Application/Service. Please clarify.

**Comment by mahesh0431** [comment]
Hi @namratasurendranath , yes, for a seamless experience, IAS is required.
